/* LOCATION */
export const SET_LOCATION = 'SET_LOCATION'
/* MESSAGES */
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
/* AUTHENTICATION */
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'
export const REGISTER_END = 'REGISTER_END'
/* ONBOARDING */
export const SET_ONBOARDING = 'SET_ONBOARDING'
export const SET_SLIDE = 'SET_SLIDE'
export const CLEAR_ONBOARDING = 'CLEAR_ONBOARDING'
/* INFOSUP */
export const SET_INFOSUP = 'SET_INFOSUP'
export const CLEAR_INFOSUP = 'CLEAR_INFOSUP'
/* PROFIL */
export const SET_PROFIL = 'SET_PROFIL'
export const CLEAR_PROFIL = 'CLEAR_PROFIL'
/* DONNEESUTILISATEUR */
export const SET_DONNEESUTILISATEUR = 'SET_DONNEESUTILISATEUR'
export const CLEAR_DONNEESUTILISATEUR = 'CLEAR_DONNEESUTILISATEUR'
/* OBJECTIF */
export const SET_OBJECTIF = 'SET_OBJECTIF'
export const CLEAR_OBJECTIF = 'CLEAR_OBJECTIF'
/* PLAN */
export const SET_PLAN = 'SET_PLAN'
export const CLEAR_PLAN = 'CLEAR_PLAN'
export const PREPARE_PLAN = 'PREPARE_PLAN'
export const UNPREPARE_PLAN = 'UNPREPARE_PLAN'
export const SET_DAY = 'SET_DAY'
export const CLEAR_DAY = 'CLEAR_DAY'
/* SEANCES */
export const SET_SEANCES = 'SET_SEANCES'
export const CLEAR_SEANCES = 'CLEAR_SEANCES'
/* COURBES */
export const SET_COURBES = 'SET_COURBES'
export const CLEAR_COURBES = 'CLEAR_COURBES'
/* ENTRAINEMENTS */
export const SET_ENTRAINEMENTS = 'SET_ENTRAINEMENTS'
export const CLEAR_ENTRAINEMENTS = 'CLEAR_ENTRAINEMENTS'
export const SET_ANALYSE = 'SET_ANALYSE'
export const CLEAR_ANALYSE = 'CLEAR_ANALYSE'
/* STATISTIQUES */
export const SET_STATISTIQUES = 'SET_STATISTIQUES'
export const CLEAR_STATISTIQUES = 'CLEAR_STATISTIQUES'
